import React, { useState } from 'react';
import { Download, Printer, Share2, Award, Activity, Building2, Users, FileText } from 'lucide-react';

const Reports = () => {
  const [reportType, setReportType] = useState('student'); // 'student' or 'institute'

  // Mock institute report data
  const mockInstituteReport = {
    name: 'DPS Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    totalStudents: 120,
    avgScore: 82,
    students: [
      { name: 'Rahul Sharma', class: '10A', sport: 'Cricket', score: 88 },
      { name: 'Priya Patel', class: '9B', sport: 'Athletics', score: 92 },
      { name: 'Amit Kumar', class: '11C', sport: 'Football', score: 75 },
      { name: 'Sneha Joshi', class: '10B', sport: 'Basketball', score: 81 },
      { name: 'Vikram Singh', class: '12A', sport: 'Swimming', score: 79 },
    ],
  };

  const handleExportPDF = async () => {
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      
      if (reportType === 'student') {
        // Student Report PDF
        doc.setFontSize(22);
        doc.setTextColor(30, 41, 59);
        doc.text('Athletic Performance Report', 20, 25);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139);
        doc.text('Academic Year 2025 - Term 2', 20, 35);
        
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(1);
        doc.line(20, 40, 190, 40);
        
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('Student Details', 20, 55);
        
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);
        doc.text('Name: John Doe', 20, 65);
        doc.text('Student ID: STU-001', 20, 73);
        doc.text('Sport: Football', 20, 81);
        doc.text('BMI: 22.5 (Normal)', 20, 89);
        
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('Performance Summary', 20, 105);
        
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);
        doc.text('Overall Score: 92%', 20, 115);
        doc.text('Fitness Level: Excellent', 20, 123);
        doc.text('Attendance: 98%', 20, 131);
        
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text('Generated by SportSync Academy', 20, 280);
      } else {
        // Institute Report PDF
        doc.setFontSize(22);
        doc.setTextColor(30, 41, 59);
        doc.text('Institute Performance Report', 20, 25);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139);
        doc.text('Generated on: ' + new Date().toLocaleDateString('en-IN'), 20, 35);
        
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(1);
        doc.line(20, 40, 190, 40);
        
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('Institute Details', 20, 55);
        
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);
        doc.text(`Name: ${mockInstituteReport.name}`, 20, 65);
        doc.text(`City: ${mockInstituteReport.city}`, 20, 73);
        doc.text(`State: ${mockInstituteReport.state}`, 20, 81);
        doc.text(`Total Students: ${mockInstituteReport.totalStudents}`, 20, 89);
        doc.text(`Average Score: ${mockInstituteReport.avgScore}%`, 20, 97);
        
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('Students List', 20, 115);
        
        // Table header
        doc.setFontSize(10);
        doc.setTextColor(255, 255, 255);
        doc.setFillColor(37, 99, 235);
        doc.rect(20, 120, 170, 8, 'F');
        doc.text('Name', 22, 126);
        doc.text('Class', 72, 126);
        doc.text('Sport', 102, 126);
        doc.text('Score', 152, 126);
        
        // Table rows
        doc.setTextColor(71, 85, 105);
        mockInstituteReport.students.forEach((s, i) => {
          const y = 136 + (i * 10);
          if (i % 2 === 0) {
            doc.setFillColor(248, 250, 252);
            doc.rect(20, y - 6, 170, 10, 'F');
          }
          doc.text(s.name, 22, y);
          doc.text(s.class, 72, y);
          doc.text(s.sport, 102, y);
          doc.text(`${s.score}%`, 152, y);
        });
        
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text('Generated by SportSync Academy', 20, 280);
      }
      
      doc.save(`${reportType}_report.pdf`);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
      alert('Failed to generate PDF. Please make sure jspdf is installed.');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-primary">Reports</h1>
          <p className="text-text-light text-sm">Generate and export professional graphical reports.</p>
        </div>
        <div className="flex gap-3">
          <button className="bg-white text-text-dark px-4 py-2 rounded-lg border border-gray-200 text-sm shadow-sm hover:bg-gray-50 transition-colors flex items-center gap-2 font-medium">
            <Share2 size={16} /> Share
          </button>
          <button className="bg-white text-text-dark px-4 py-2 rounded-lg border border-gray-200 text-sm shadow-sm hover:bg-gray-50 transition-colors flex items-center gap-2 font-medium">
            <Printer size={16} /> Print
          </button>
          <button
            onClick={handleExportPDF}
            className="bg-secondary text-white px-4 py-2 rounded-lg text-sm shadow-md hover:bg-primary transition-colors flex items-center gap-2 font-medium"
          >
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      {/* Report Type Toggle */}
      <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-100">
        <div className="flex items-center gap-6">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="radio"
              name="reportType"
              value="student"
              checked={reportType === 'student'}
              onChange={(e) => setReportType(e.target.value)}
              className="w-4 h-4 text-secondary focus:ring-secondary"
            />
            <span className={`text-sm font-semibold ${reportType === 'student' ? 'text-text-dark' : 'text-text-light'}`}>
              Student Report
            </span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="radio"
              name="reportType"
              value="institute"
              checked={reportType === 'institute'}
              onChange={(e) => setReportType(e.target.value)}
              className="w-4 h-4 text-secondary focus:ring-secondary"
            />
            <span className={`text-sm font-semibold ${reportType === 'institute' ? 'text-text-dark' : 'text-text-light'}`}>
              Institute Report
            </span>
          </label>
        </div>
      </div>

      {reportType === 'student' ? (
        /* ===== STUDENT REPORT (existing UI) ===== */
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 max-w-4xl mx-auto">
          {/* Report Header */}
          <div className="border-b-4 border-secondary pb-6 mb-8 flex justify-between items-start">
            <div>
              <h2 className="text-3xl font-black text-primary uppercase tracking-tight">Athletic Performance Report</h2>
              <p className="text-gray-500 mt-1 font-medium">Academic Year 2025 - Term 2</p>
            </div>
            <div className="text-right">
              <div className="w-12 h-12 bg-secondary rounded-xl ml-auto mb-2 flex items-center justify-center">
                <Award className="text-white" size={24} />
              </div>
              <p className="font-bold text-primary">SportSync Academy</p>
            </div>
          </div>

          {/* Student Profile Summary */}
          <div className="flex gap-8 mb-10">
            <div className="w-32 h-32 rounded-2xl bg-gray-100 overflow-hidden shrink-0 border-4 border-white shadow-lg">
              <img src="https://ui-avatars.com/api/?name=John+Doe&background=2563EB&color=fff&size=200" alt="Student" />
            </div>
            <div className="grid grid-cols-2 gap-x-12 gap-y-4 flex-1">
              <div>
                <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">Student Name</p>
                <p className="text-lg font-bold text-text-dark">John Doe</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">Student ID</p>
                <p className="text-lg font-bold text-text-dark">STU-001</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">Primary Sport</p>
                <p className="text-lg font-bold text-text-dark">Football</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">BMI & Category</p>
                <p className="text-lg font-bold text-text-dark">22.5 (Normal)</p>
              </div>
            </div>
          </div>

          {/* Grades Block */}
          <div className="grid grid-cols-3 gap-6 mb-10">
            <div className="bg-green-50 p-6 rounded-2xl border border-green-100 text-center">
              <p className="text-sm font-bold text-green-800 uppercase tracking-widest mb-2">Overall Score</p>
              <h3 className="text-4xl font-black text-green-600">92%</h3>
            </div>
            <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100 text-center">
              <p className="text-sm font-bold text-blue-800 uppercase tracking-widest mb-2">Fitness Level</p>
              <h3 className="text-3xl font-black text-blue-600 mt-1">Excellent</h3>
            </div>
            <div className="bg-orange-50 p-6 rounded-2xl border border-orange-100 text-center">
              <p className="text-sm font-bold text-orange-800 uppercase tracking-widest mb-2">Attendance</p>
              <h3 className="text-4xl font-black text-orange-600">98%</h3>
            </div>
          </div>

          {/* AI Insight Placeholder */}
          <div className="bg-gray-50 p-6 rounded-2xl border border-gray-200">
            <h4 className="font-bold text-text-dark mb-2 flex items-center gap-2">
              <Activity size={18} className="text-secondary" /> Performance Insights
            </h4>
            <p className="text-gray-600 italic">"Student shows excellent stamina improvement in Term 2. Outstanding endurance levels maintained during high-intensity training. Needs slight focus on flexibility to prevent future injuries."</p>
          </div>
        </div>
      ) : (
        /* ===== INSTITUTE REPORT ===== */
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 max-w-4xl mx-auto">
          {/* Report Header */}
          <div className="border-b-4 border-secondary pb-6 mb-8 flex justify-between items-start">
            <div>
              <h2 className="text-3xl font-black text-primary uppercase tracking-tight">Institute Performance Report</h2>
              <p className="text-gray-500 mt-1 font-medium">Generated on: {new Date().toLocaleDateString('en-IN')}</p>
            </div>
            <div className="text-right">
              <div className="w-12 h-12 bg-secondary rounded-xl ml-auto mb-2 flex items-center justify-center">
                <Building2 className="text-white" size={24} />
              </div>
              <p className="font-bold text-primary">SportSync Academy</p>
            </div>
          </div>

          {/* Institute Info */}
          <div className="grid grid-cols-2 gap-x-12 gap-y-4 mb-10">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">Institute Name</p>
              <p className="text-lg font-bold text-text-dark">{mockInstituteReport.name}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">City</p>
              <p className="text-lg font-bold text-text-dark">{mockInstituteReport.city}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">State</p>
              <p className="text-lg font-bold text-text-dark">{mockInstituteReport.state}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-bold mb-1">Total Students</p>
              <p className="text-lg font-bold text-text-dark">{mockInstituteReport.totalStudents}</p>
            </div>
          </div>

          {/* Score Summary */}
          <div className="grid grid-cols-2 gap-6 mb-10">
            <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100 text-center">
              <p className="text-sm font-bold text-blue-800 uppercase tracking-widest mb-2">Average Score</p>
              <h3 className="text-4xl font-black text-blue-600">{mockInstituteReport.avgScore}%</h3>
            </div>
            <div className="bg-green-50 p-6 rounded-2xl border border-green-100 text-center">
              <p className="text-sm font-bold text-green-800 uppercase tracking-widest mb-2">Total Students</p>
              <h3 className="text-4xl font-black text-green-600">{mockInstituteReport.totalStudents}</h3>
            </div>
          </div>

          {/* Students List Table */}
          <div className="mb-6">
            <h3 className="text-lg font-bold text-primary mb-4 flex items-center gap-2">
              <Users size={20} className="text-accent" /> Students List
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-gray-50 text-text-light text-xs uppercase tracking-wider border-b border-gray-100">
                    <th className="p-4 font-semibold">#</th>
                    <th className="p-4 font-semibold">Name</th>
                    <th className="p-4 font-semibold">Class</th>
                    <th className="p-4 font-semibold">Sport</th>
                    <th className="p-4 font-semibold">Score</th>
                  </tr>
                </thead>
                <tbody className="text-sm divide-y divide-gray-100">
                  {mockInstituteReport.students.map((student, index) => (
                    <tr key={index} className="hover:bg-blue-50/30 transition-colors">
                      <td className="p-4 text-text-light">{index + 1}</td>
                      <td className="p-4 font-semibold text-text-dark">{student.name}</td>
                      <td className="p-4 text-text-dark">{student.class}</td>
                      <td className="p-4">
                        <span className="inline-block px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-semibold">
                          {student.sport}
                        </span>
                      </td>
                      <td className="p-4">
                        <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${
                          student.score >= 85 ? 'bg-green-100 text-green-700' :
                          student.score >= 70 ? 'bg-blue-100 text-blue-700' :
                          'bg-yellow-100 text-yellow-700'
                        }`}>
                          {student.score}%
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Footer Insight */}
          <div className="bg-gray-50 p-6 rounded-2xl border border-gray-200">
            <h4 className="font-bold text-text-dark mb-2 flex items-center gap-2">
              <Activity size={18} className="text-secondary" /> Institute Insights
            </h4>
            <p className="text-gray-600 italic">"The institute shows strong overall performance with an average score of {mockInstituteReport.avgScore}%. Students are actively engaged across multiple sports categories with consistent improvement trends."</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;
